name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Build
        run: dotnet build --configuration Release --verbosity m
      - name: Test
        run: dotnet test --nologo -v q
